### ISSUE TITLE
dependency missing

### ISSUE THREAD

**Issue by seanyinx** [IG-Group/ig-webapi-java-sample#5]
```
[ERROR] Failed to execute goal on project ig-webapi-java-client: Could not resolve dependencies for project com.iggroup.webapi.samples:ig-webapi-java-client:jar:2.2.0-SNAPSHOT: Could not find artifact com.lightstreamer:sdk.client.java.se:jar:6.0.2.20160510 in lightstreamer (http://www.lightstreamer.com/repo/maven) -> [Help 1]
```

it seems that the java client dependency is no longer available on lightstreamer.com.

**Comment by vagadiya** [comment]
I remember having a similar problem myself when I first cloned the repo.  Try running a mvn clean first, this should install the lightstreamer sdk client dependency from the lib folder into your local maven repository.

**Comment by seanyinx** [comment]
@vagadiya Thank you! It works. I should have looked at the project readme more carefully.

**Comment by ireay** [comment]
Cool. Glad that you got this working.
